// Generated by gencpp from file px4_cmd/Command.msg
// DO NOT EDIT!


#ifndef PX4_CMD_MESSAGE_COMMAND_H
#define PX4_CMD_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_cmd
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , Vehicle(0)
    , Mode(0)
    , Move_frame(0)
    , Move_mode(0)
    , desire_cmd()
    , yaw_cmd(0.0)
    , ext_total_time(0.0)
    , ext_time(0.0)  {
      desire_cmd.assign(0.0);
  }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Vehicle(0)
    , Mode(0)
    , Move_frame(0)
    , Move_mode(0)
    , desire_cmd()
    , yaw_cmd(0.0)
    , ext_total_time(0.0)
    , ext_time(0.0)  {
  (void)_alloc;
      desire_cmd.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Vehicle_type;
  _Vehicle_type Vehicle;

   typedef uint8_t _Mode_type;
  _Mode_type Mode;

   typedef uint8_t _Move_frame_type;
  _Move_frame_type Move_frame;

   typedef uint8_t _Move_mode_type;
  _Move_mode_type Move_mode;

   typedef boost::array<float, 3>  _desire_cmd_type;
  _desire_cmd_type desire_cmd;

   typedef float _yaw_cmd_type;
  _yaw_cmd_type yaw_cmd;

   typedef float _ext_total_time_type;
  _ext_total_time_type ext_total_time;

   typedef float _ext_time_type;
  _ext_time_type ext_time;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(Multicopter)
  #undef Multicopter
#endif
#if defined(_WIN32) && defined(FixWing)
  #undef FixWing
#endif
#if defined(_WIN32) && defined(Idle)
  #undef Idle
#endif
#if defined(_WIN32) && defined(Takeoff)
  #undef Takeoff
#endif
#if defined(_WIN32) && defined(Move)
  #undef Move
#endif
#if defined(_WIN32) && defined(Hover)
  #undef Hover
#endif
#if defined(_WIN32) && defined(Loiter)
  #undef Loiter
#endif
#if defined(_WIN32) && defined(Trajectory)
  #undef Trajectory
#endif
#if defined(_WIN32) && defined(User_define)
  #undef User_define
#endif
#if defined(_WIN32) && defined(Gliding)
  #undef Gliding
#endif
#if defined(_WIN32) && defined(ENU)
  #undef ENU
#endif
#if defined(_WIN32) && defined(BODY)
  #undef BODY
#endif
#if defined(_WIN32) && defined(XYZ_POS)
  #undef XYZ_POS
#endif
#if defined(_WIN32) && defined(XY_VEL_Z_POS)
  #undef XY_VEL_Z_POS
#endif
#if defined(_WIN32) && defined(XYZ_VEL)
  #undef XYZ_VEL
#endif
#if defined(_WIN32) && defined(XYZ_REL_POS)
  #undef XYZ_REL_POS
#endif

  enum {
    Multicopter = 0u,
    FixWing = 1u,
    Idle = 0u,
    Takeoff = 1u,
    Move = 2u,
    Hover = 3u,
    Loiter = 3u,
    Trajectory = 4u,
    User_define = 5u,
    Gliding = 6u,
    ENU = 0u,
    BODY = 1u,
    XYZ_POS = 0u,
    XY_VEL_Z_POS = 1u,
    XYZ_VEL = 2u,
    XYZ_REL_POS = 3u,
  };


  typedef boost::shared_ptr< ::px4_cmd::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_cmd::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::px4_cmd::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::px4_cmd::Command > CommandPtr;
typedef boost::shared_ptr< ::px4_cmd::Command const> CommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_cmd::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_cmd::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_cmd::Command_<ContainerAllocator1> & lhs, const ::px4_cmd::Command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Vehicle == rhs.Vehicle &&
    lhs.Mode == rhs.Mode &&
    lhs.Move_frame == rhs.Move_frame &&
    lhs.Move_mode == rhs.Move_mode &&
    lhs.desire_cmd == rhs.desire_cmd &&
    lhs.yaw_cmd == rhs.yaw_cmd &&
    lhs.ext_total_time == rhs.ext_total_time &&
    lhs.ext_time == rhs.ext_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_cmd::Command_<ContainerAllocator1> & lhs, const ::px4_cmd::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_cmd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_cmd::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_cmd::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_cmd::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_cmd::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_cmd::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_cmd::Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_cmd::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "211bf51948b6ca1e6ae5e6c13161b0e1";
  }

  static const char* value(const ::px4_cmd::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x211bf51948b6ca1eULL;
  static const uint64_t static_value2 = 0x6ae5e6c13161b0e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_cmd::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_cmd/Command";
  }

  static const char* value(const ::px4_cmd::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_cmd::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 载具\n"
"uint8 Vehicle\n"
"# 载具列举\n"
"uint8 Multicopter = 0 \n"
"uint8 FixWing = 1\n"
"\n"
"## 控制命令模式 \n"
"uint8 Mode\n"
"# Mode 控制模式枚举\n"
"uint8 Idle = 0\n"
"uint8 Takeoff = 1\n"
"uint8 Move = 2\n"
"uint8 Hover = 3\n"
"uint8 Loiter = 3\n"
"uint8 Trajectory = 4\n"
"uint8 User_define = 5\n"
"uint8 Gliding = 6       ### 固定翼滑行模式\n"
"\n"
"## 移动命令坐标系\n"
"uint8 Move_frame\n"
"## 坐标系枚举\n"
"uint8 ENU = 0           ### 惯性系\n"
"uint8 BODY = 1          ### 机体系\n"
"\n"
"## 移动命令下的子模式\n"
"uint8 Move_mode\n"
"## 移动命令下的子模式枚举\n"
"uint8 XYZ_POS = 0       ### 定点控制(绝对位置)\n"
"uint8 XY_VEL_Z_POS = 1  ### 定高速度控制 - 仅旋翼\n"
"uint8 XYZ_VEL = 2       ### 速度控制 - 仅旋翼\n"
"uint8 XYZ_REL_POS = 3   ### 定点控制(相对位置)\n"
"\n"
"## 指令输入\n"
"float32[3] desire_cmd    ### [m] [m/s] [m/s^2]\n"
"float32 yaw_cmd          ### [rad]\n"
"float32 ext_total_time   ### 外部指令运行总时间 [s]\n"
"float32 ext_time         ### 外部指令当前运行时间 [s]\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_cmd::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_cmd::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Vehicle);
      stream.next(m.Mode);
      stream.next(m.Move_frame);
      stream.next(m.Move_mode);
      stream.next(m.desire_cmd);
      stream.next(m.yaw_cmd);
      stream.next(m.ext_total_time);
      stream.next(m.ext_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_cmd::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_cmd::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Vehicle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Vehicle);
    s << indent << "Mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Mode);
    s << indent << "Move_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Move_frame);
    s << indent << "Move_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Move_mode);
    s << indent << "desire_cmd[]" << std::endl;
    for (size_t i = 0; i < v.desire_cmd.size(); ++i)
    {
      s << indent << "  desire_cmd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.desire_cmd[i]);
    }
    s << indent << "yaw_cmd: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_cmd);
    s << indent << "ext_total_time: ";
    Printer<float>::stream(s, indent + "  ", v.ext_total_time);
    s << indent << "ext_time: ";
    Printer<float>::stream(s, indent + "  ", v.ext_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_CMD_MESSAGE_COMMAND_H
