/**************************************************************************
This file is generated by px4_cmd gui controller for external command, 
if you don't know how this file works, please don't edit it.
**************************************************************************/
#ifndef VEHICEL_EXTERNAL_COMMAND_H
#define VEHICEL_EXTERNAL_COMMAND_H
#include <vector>
#include <string>
#include <thread>
#include <ros/ros.h>
#include <px4_cmd/Command.h>
#include <tf/LinearMath/Quaternion.h>
#include <tf/LinearMath/Transform.h>
#include <tf/transform_datatypes.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/TwistStamped.h>

#define PI 3.14159265358979323846
using namespace std;

class vehicle_external_command
{
    private:
        bool ros_shutdown_flag = false;
        double update_time = 0.1;
        double init_R;
        double init_P;
        double init_Y;
        px4_cmd::Command external_cmd;
        tf::Quaternion quat;
        double R;
        double P;
        double Y;
        ros::Subscriber pos_pose_sub;
        ros::Subscriber vel_angle_rate_sub;
        ros::Publisher ext_cmd_pub;
        void pos_cb(const geometry_msgs::PoseStamped::ConstPtr &msg);
        void vel_cb(const geometry_msgs::TwistStamped::ConstPtr &msg);
        void ros_thread_fun();

    public:
        double init_x;
        double init_y;
        double init_z;
        double position[3];
        double attitude[3];
        double velocity[3];
        double angle_rate[3];
        void start(string node);
        void set_position(double x, double y, double z, int frame);
        void set_position(double x, double y, double z, double yaw, int frame);
        void set_velocity(double vx, double vy, double vz, int frame);
        void set_velocity(double vx, double vy, double vz, double yaw, int frame);
        void set_velocity_with_height(double vx, double vy, double z, int frame);
        void set_velocity_with_height(double vx, double vy, double z, double yaw, int frame);
        void shutdown();
};
#endif